title: Adem ÖZCAN
author: Adem Furkan ÖZCAN
email: info@ademfurkan.com
description: >-
    Flutter ile uygulama geliştiriyorum, vaktim oldukça blog yazıyorum ve hobi olarak siber güvenlikle uğraşıyorum.
show_excerpts: false
baseurl: "https://adem68.github.io/"
url: "blog/"
twitter_username: AdemOzcan68
github_username: Adem68
markdown: kramdown
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
 - jekyll-sitemap
 
paginate: 5
paginate_path: "/page:num/"
permalink: /:title

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag
gist:
  noscript: false
# jekyll-dash date format
dash:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/AdemOzcan68
      icon: twitter-square
      color: cyan
    - url: https://github.com/Adem68
      icon: github-square
      color: blue
    - url: https://t.me/Adem68
      icon: telegram
      color: orange
